axon:
  kafka:
    clientid: myproducer
    defaulttopic: mydefaulttopic
    producer:
      retries: 5
      bootstrapservers:
         - 127.0.0.1:9092
      transaction-id-prefix: clxtrx

logging:
  level:
    ROOT: DEBUG
